name: Vale Lint

on:
  pull_request:
    paths:
      - '**/*.md'  # Only trigger if Markdown files are touched
  push:
    branches-ignore:
      - main
    paths:
      - '**/*.md'

jobs:
  vale:
    name: Vale Lint Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Vale
        run: |
          VALE_VERSION="3.11.2"
          curl -sL "https://github.com/errata-ai/vale/releases/download/v${VALE_VERSION}/vale_${VALE_VERSION}_Linux_64-bit.tar.gz" -o vale.tar.gz
          tar -xzf vale.tar.gz
          sudo mv vale /usr/local/bin/
          vale --version
      - name: Install Vale styles
        run: |
            vale install Google
      - name: Get list of changed files
        id: changed
        uses: tj-actions/changed-files@v44

      - name: Run Vale on changed Markdown files
        run: |
          echo "Checking changed Markdown files..."
          run_vale=false
          for file in ${{ steps.changed.outputs.all_changed_files }}; do
            if [[ "$file" == *.md ]]; then
              echo "Linting $file"
              vale --config=".github/linters/.vale.ini" "$file"
              run_vale=true
            fi
          done

          if [ "$run_vale" = false ]; then
            echo "No Markdown files to lint. Skipping."
            exit 0
          fi
